CUDA_VISIBLE_DEVICES=1 python /oak/stanford/groups/akundaje/abuen/spatial/spatial-gnn/scripts/go_causal_interaction.py \
    --dataset aging_coronal \
    --base_path /oak/stanford/groups/akundaje/abuen/spatial/spatial-gnn/data/raw \
    --k_hop 2 \
    --augment_hop 2 \
    --center_celltypes "T cell,NSC,Pericyte" \
    --node_feature "expression" \
    --inject_feature "none" \
    --learning_rate 0.0001 \
    --loss "weightedl1" \
    --epochs 50 \
    --pairs_path /oak/stanford/groups/akundaje/abuen/spatial/spatial-gnn/pairs \
    --perturb_approach "multiplier" \
    --num_props 2 \
    --train_or_test "test"
